apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k743x5fos-nodejs
  janus-idp.io/tekton: k743x5fos-nodejs
  backstage.io/kubernetes-id: k743x5fos-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k743x5fos-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
